### ISSUE TITLE
Docker doesn't install on Windows

### ISSUE THREAD

**Issue by sishtiaq** [masoncusack/BuildYourOwnAPI#1]
I was in a state where Docker was not completely installing: it kept on asking me to manually install containers. I would tick the feature on my machine, restart , and after restarting it wouldn't be there again. 

https://github.com/docker/for-win/issues/1631 helped me: in Hyper-V turn on MobyVM manually.

**Comment by masoncusack** [comment]
Thanks, I will add this to the README as potential fix.

**Comment by masoncusack** [comment]
Updated the README with this fix suggestion on [latest commit](https://github.com/masoncusack/BuildYourOwnAPI/commit/d63ec2f2d0c671cfabe5a935b90176660d6655b3). :) Thanks again!
